// Generated by CoffeeScript 1.3.1
(function() {
  var Holder;

  Holder = (function() {

    Holder.name = 'Holder';

    function Holder($) {
      this.$ = $;
    }

    Holder.prototype.hold = function() {
      return this;
    };

    Holder.prototype.fire = function(callback) {
      callback();
      return this;
    };

    return Holder;

  })();

  $.hold = function() {
    return new Holder($);
  };

}).call(this);
